databases:
  - name: acp-db
    databaseName: acp_invest
    plan: free # Gratuit pendant 90 jours

services:
  # 2. Le Backend FastAPI
  - type: web
    name: acp-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: acp-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: acp-frontend
          property: host
      - key: SECRET_KEY
        generateValue: true
    plan: free

  # 3. Le Frontend React (Vite)
  - type: web
    name: acp-frontend
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: acp-backend
          property: host
    plan: free